package HelloModule;


/**
* HelloModule/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloModule.idl
* Thursday, 18 April, 2024 4:00:12 PM IST
*/

public interface HelloOperations 
{
  String print_hello (String s);
} // interface HelloOperations
