package HelloModule;


/**
* HelloModule/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloModule.idl
* Tuesday, 23 April, 2024 10:50:08 PM IST
*/

public interface HelloOperations 
{
  String print_hello (String s);
} // interface HelloOperations
